query AllNews($first: IntType = 500, $skip: IntType = 0) {
	allNews(first: $first, skip: $skip, orderBy: _createdAt_DESC) {
		id
		title
		text(markdown: false)
		image {
			...ImageFragment
		}
		pdf {
			...FileFragment
		}
		link
		_createdAt
	}
	_allNewsMeta {
		count
	}
}
