query Start {
	start {
		id
		text(markdown: false)
		imageCityPlanning {
			...ImageFragment
		}
		imageCulturePolitics {
			...ImageFragment
		}
		imageOrganizationDevelopment {
			...ImageFragment
		}
		imageTexts {
			...ImageFragment
		}
	}
}
