query AllWhats {
	allWhats {
		id
		title
		intro(markdown: false)
	}
}

query AllWhatExamples {
	whatExamples: allWhatExamples {
		...WhatExampleFragment
	}
}

query WhatExamples($typeId: ItemId!) {
	whatExamples: allWhatExamples(filter: { whatType: { eq: $typeId } }) {
		...WhatExampleFragment
	}
}

query AllWhatTypes {
	whats: allWhats {
		id
		title
		intro(markdown: false)
		slug
	}
}
